multitenancy:
  tenants:
  - name: tenant_1
    default: true
    url: jdbc:mysql://localhost:3306/automation_test
    username: root
    password: elnino
    driver-class-name: com.mysql.jdbc.Driver
  - name: tenant_2
    default: false
    url: jdbc:oracle:thin:@//localhost:1521:xe
    username: SYS
    password: elnino
    driver-class-name: oracle.jdbc.driver.OracleDriver
    dialect: 
    
server:
  port: 8083